name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # update per 6 hrs
  workflow_dispatch:       # allow manual update

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake.svg

    steps:
      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ErdunE
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
